contacts = {'Aanderaa':"ysi.repairs@xyleminc.com",
			'AML Oceanographic':"service@amloceanographic.com",
            'ASL Environmental':"jbuermans@aslenv.com",
            'Axys':"AXYSCustomerService@axys.com",
            'Nortek':"ussupport@nortek.no",
            'PP Systems':"bf@ppsystems.com",
            'Pro-Oceanus':"admin@pro-oceanus.com",
            'Satlantic':"service@seabird.com",
            'Seabird':"service@seabird.com",
            'Sea Bird':"service@seabird.com",
            'Sunburst':"techsupport@sunburst.com",
            'Teledyne RDI':"rdi.csadmin@teledyne.com",
            'Wet Labs':"service@wetlabs.com"}
